### ISSUE TITLE
Re-distribution of the package is cumbersome (i.e. distribute by an installer)

### ISSUE THREAD

**Issue by 130s** [130s/docker_vcstool#13]

**Comment by 130s** [comment]
I'm ok to start from making a `pip` installer.
- For now going simple.
- Initially I thought of skipping to create `wheel` https://realpython.com/python-wheels/ (so building each time on the user's platform), but later reading through https://realpython.com/python-wheels/#calling-all-developers-build-your-wheels, I was reminded of "usability". The very core thing why ROS was so good in the beginning. I should stick to that. Will do `wheel`.
   - Indeed installation of non-`wheel` pkg failed.
      <details><summary>Example failure of pip installing uwsgi. This looks an exact example of why I should consider usability.</summary>
      
      ```
      # pip install 'uwsgi==2.0.*'
      Collecting uwsgi==2.0.*
        Downloading uwsgi-2.0.22.tar.gz (809 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 809.7/809.7 kB 9.1 MB/s eta 0:00:00
        Preparing metadata (setup.py) ... done
      Building wheels for collected packages: uwsgi
        Building wheel for uwsgi (setup.py) ... error
        error: subprocess-exited-with-error
        
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [43 lines of output]
            /usr/local/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'descriptions'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib
            copying uwsgidecorators.py -> build/lib
            installing to build/bdist.linux-x86_64/wheel
            running install
            using profile: buildconf/default.ini
            detected include path: ['/usr/include', '/usr/local/include']
            Traceback (most recent call last):
              File "/tmp/pip-install-1tyvyk0o/uwsgi_278414b86d0d40a89c5cb702d7ed4a36/uwsgiconfig.py", line 750, in __init__
                gcc_version_components = gcc_version.split('.')
            AttributeError: 'NoneType' object has no attribute 'split'
            
            During handling of the above exception, another exception occurred:
            
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-1tyvyk0o/uwsgi_278414b86d0d40a89c5cb702d7ed4a36/setup.py", line 117, in <module>
                setup(
              File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
                return distutils.core.setup(**attrs)
              File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
                dist.run_commands()
              File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
                self.run_command(cmd)
              File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
                cmd_obj.run()
              File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 378, in run
                self.run_command("install")
              File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
                cmd_obj.run()
              File "/tmp/pip-install-1tyvyk0o/uwsgi_278414b86d0d40a89c5cb702d7ed4a36/setup.py", line 77, in run
                conf = uc.uConf(get_profile())
              File "/tmp/pip-install-1tyvyk0o/uwsgi_278414b86d0d40a89c5cb702d7ed4a36/uwsgiconfig.py", line 758, in __init__
                raise Exception("you need a C compiler to build uWSGI")
            Exception: you need a C compiler to build uWSGI
            [end of output]
        
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for uwsgi
        Running setup.py clean for uwsgi
      Failed to build uwsgi
      ERROR: Could not build wheels for uwsgi, which is required to install pyproject.toml-based projects
      ```
      </details>

# CoS
- [ ] Installer created with minimal config. Manual test ok.
- [ ] Installer created with `wheel`. Manual test ok.

WIP https://github.com/kinu-garage/docker_vcstool/pull/17

**Comment by 130s** [comment]
https://realpython.com/python-wheels/#making-sure-your-wheels-spin-right suggests testing a `wheel` on https://test.pypi.org, but the command fails.

<details><summary>log</summary>

```
# twine upload --verbose       --repository-url https://test.pypi.org/legacy/       docker_vcs_tools-0.1.0-py3-none-any.whl 
Uploading distributions to https://test.pypi.org/legacy/                     
INFO     docker_vcs_tools-0.1.0-py3-none-any.whl (14.5 KB) 
INFO     Querying keyring for username                            
Enter your username: noodle_bind                          
INFO     Querying keyring for password             
WARNING  Error getting password from keyring       
         Traceback (most recent call last):                       
           File "/usr/local/lib/python3.9/site-packages/twine/auth.py", line 74, in get_password_from_keyring                          
             return cast(str, keyring.get_password(system, username))   
           File "/usr/local/lib/python3.9/site-packages/keyring/core.py", line 56, in get_password    
             return get_keyring().get_password(service_name, username)         
           File "/usr/local/lib/python3.9/site-packages/keyring/backends/fail.py", line 28, in get_password                            
             raise NoKeyringError(msg)                            
         keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended  
         backends. See https://pypi.org/project/keyring for details.    
Enter your password: 
INFO     username: noodle_bind                            
INFO     password: <hidden>                        
Uploading docker_vcs_tools-0.1.0-py3-none-any.whl  
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 kB • 00:01 • 7.8 MB/s                         
INFO     Response from https://test.pypi.org/legacy/:             
         403 Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.    
INFO     <html>                     
          <head>     
           <title>403 Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.</title>
          </head>    
          <body>     
           <h1>403 Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.</h1>      
           Access was denied to this resource.<br/><br/>                
         Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.        
          </body>    
         </html>     
ERROR    HTTPError: 403 Forbidden from https://test.pypi.org/legacy/    
         Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.        
# twine upload --verbose       --repository-url https://test.pypi.org/legacy/       docker_vcs_tools-0.1.0-py3-none-any.whl 
```
</details>

Turned out that test.pypi.org does NOT share the user accounts from pypi.org, so I made an accounton test.pypi.org, verified email address.

<details><summary>Now finally obtained an actual review of my wheel. Nice!</summary>

```
# twine upload --verbose       --repository-url https://test.pypi.org/legacy/       docker_vcs_tools-0.1.0-py3-none-any.whl 
Uploading distributions to https://test.pypi.org/legacy/
INFO     docker_vcs_tools-0.1.0-py3-none-any.whl (14.5 KB)               
INFO     Querying keyring for username             
Enter your username: noodle_bind
INFO     Querying keyring for password             
WARNING  Error getting password from keyring       
         Traceback (most recent call last):        
           File "/usr/local/lib/python3.9/site-packages/twine/auth.py", line 74, in get_password_from_keyring        
             return cast(str, keyring.get_password(system, username))    
           File "/usr/local/lib/python3.9/site-packages/keyring/core.py", line 56, in get_password    
             return get_keyring().get_password(service_name, username)   
           File "/usr/local/lib/python3.9/site-packages/keyring/backends/fail.py", line 28, in get_password          
             raise NoKeyringError(msg)             
         keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended  
         backends. See https://pypi.org/project/keyring for details.     
Enter your password: 
INFO     username: noodle_bind                            
INFO     password: <hidden>                        
Uploading docker_vcs_tools-0.1.0-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 kB • 00:00 • 9.4 MB/s
INFO     Response from https://test.pypi.org/legacy/:                    
         400 Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: Apache2 License' is not a valid classifier.             
INFO     <html>       
          <head>      
           <title>400 Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: Apache2 License' is not a valid classifier.</title>                         
          </head>     
          <body>      
           <h1>400 Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: Apache2 License' is not a valid classifier.</h1>  
           The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>                            
         Invalid value for classifiers. Error: Classifier &#x27;License :: OSI Approved :: Apache2 License&#x27; is not a valid classifier.       
          </body>     
         </html>      
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/   
         Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: Apache2 License' is not a valid classifier.

```
</details>

**Comment by 130s** [comment]
Set up MFA and created `$HOME/.pypirc` but `twine` still fails to upload.

<details><summary>http error code 401</summary>

```
# twine upload --verbose       --repository-url https://test.pypi.org/legacy/       docker_vcs_tools-0.1.0-py3-none-any.whl                 
Uploading distributions to https://test.pypi.org/legacy/       
INFO     docker_vcs_tools-0.1.0-py3-none-any.whl (13.6 KB)     
INFO     Querying keyring for username             
Enter your username: noodle_bind                          
INFO     Querying keyring for password             
WARNING  Error getting password from keyring                   
         Traceback (most recent call last):                    
           File "/usr/local/lib/python3.9/site-packages/twine/auth.py", line 74, in get_password_from_keyring                 
             return cast(str, keyring.get_password(system, username))                                 
           File "/usr/local/lib/python3.9/site-packages/keyring/core.py", line 56, in get_password    
             return get_keyring().get_password(service_name, username)                 
           File "/usr/local/lib/python3.9/site-packages/keyring/backends/fail.py", line 28, in get_password                   
             raise NoKeyringError(msg)             
         keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended  
         backends. See https://pypi.org/project/keyring for details.                                  
Enter your password: 
INFO     username: noodle_bind                            
INFO     password: <hidden>                        
Uploading docker_vcs_tools-0.1.0-py3-none-any.whl  
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 kB • 00:00 • 6.5 MB/s
INFO     Response from https://test.pypi.org/legacy/:          
         401 User noodle_bind has two factor auth enabled, an API Token or Trusted Publisher must be used to upload in place of password.                                   
INFO     <html>                                    
          <head>                                   
           <title>401 User noodle_bind has two factor auth enabled, an API Token or Trusted Publisher must be used to upload in place of password.</title>                  
          </head>                                  
          <body>                                   
           <h1>401 User noodle_bind has two factor auth enabled, an API Token or Trusted Publisher must be used to upload in place of password.</h1>                        
           This server could not verify that you are authorized to access the document you requested.  Either you supplied the wrong credentials (e.g., bad password), or your browser does not understand  
         how to supply the credentials required.<br/><br/>     
         User noodle_bind has two factor auth enabled, an API Token or Trusted Publisher must be used to upload in place of password.
          </body>                                  
         </html>                                   
ERROR    HTTPError: 401 Unauthorized from https://test.pypi.org/legacy/                               
         User noodle_bind has two factor auth enabled, an API Token or Trusted Publisher must be used to upload in place of password.
```
</details>

Turned out in `.pypirc` I defined the target repo as `testpypi` but in CLI I used `--repository-url` with URL. 

```
[testpypi]
repository = https://test.pypi.org/legacy/
username = __token__
password = (HIDDEN)
```

Swapping to `twine upload --verbose        --repository testpypi` seems to have worked finally.

<details><summary>Yay</summary>

```
# twine upload --verbose        --repository testpypi     docker_vcs_tools-0.1.0-py3-none-any.whl 
INFO     Using configuration from /root/.pypirc 
Uploading distributions to https://test.pypi.org/legacy/
INFO     docker_vcs_tools-0.1.0-py3-none-any.whl (13.6 KB)                             
INFO     username set from config file          
INFO     password set from config file          
INFO     username: __token__                    
INFO     password: <hidden>                     
Uploading docker_vcs_tools-0.1.0-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 kB • 00:00 • 279.9 kB/s
INFO     Response from https://test.pypi.org/legacy/:                                  
         200 OK                                 

View at:
https://test.pypi.org/project/docker-vcs-tools/0.1.0/
```
</details>
