### ISSUE TITLE
"AttributeError: module 'docker' has no attribute 'APIClient'"

### ISSUE THREAD

**Issue by 130s** [130s/docker_vcstool#4]
Haven't seen this a few days before but it started happening.
```
$ ./docker_builder_vcs.py --dockerfile Dockerfile_ros-melodic --docker_base_img ros:melodic-ros-base --volume_build /home/noodler/cws/src --rm_intermediate --debug
INFO:root:'volume_build' is set. All files and folders under the volume dir '{}' are to be copied into the workspace.
INFO:root:File to be copied: 'Dockerfile_ros-melodic'
INFO:root:Files are copied into a temp dir: '['Dockerfile_ros-melodic']'
DEBUG:root:path_dockerfile: Dockerfile_ros-melodic, base_docker_img: ros:melodic-ros-base
WARNING:root:As of 2021/02 entrypoint is statically embedded in a Docker image as resolving entrypoint seems not easy.
Traceback (most recent call last):
  File "./docker_builder_vcs.py", line 183, in docker_build
    _log = self._docker_build_exec_api(                 
  File "./docker_builder_vcs.py", line 92, in _docker_build_exec_api
    dck_api = docker.APIClient()
```

**Comment by 130s** [comment]
Got a hint from an unrelated thread https://github.com/ansible-community/molecule/issues/771#issuecomment-286362191.

Removed `docker-py` and the error went away. Verified I'm using Docker-py from `apt` pkg, `python3-docker`.
On this host I'm working on multiple Python - Docker prjs so I might have installed something undesirable.
```
$ pip3 show docker-py
Name: docker-py
Version: 1.10.6
Summary: Python client for Docker.
Home-page: https://github.com/docker/docker-py/
Author: Joffrey F
Author-email: joffrey@docker.com
License: UNKNOWN
Location: /home/n130s/.local/lib/python3.8/site-packages
Requires: requests, six, docker-pycreds, websocket-client
Required-by: 
n130s@130s-p50:~/link/cws_utakata/src/130s/docker_vcstool/docker_vcs_tools$ pip3 uninstall docker-py
Found existing installation: docker-py 1.10.6
Uninstalling docker-py-1.10.6:
  Would remove:
    /home/n130s/.local/lib/python3.8/site-packages/docker/*
    /home/n130s/.local/lib/python3.8/site-packages/docker_py-1.10.6.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled docker-py-1.10.6

$ apt-cache policy python3-docker
python3-docker:
  Installed: 4.1.0-1
  Candidate: 4.1.0-1
  Version table:
 *** 4.1.0-1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal/universe i386 Packages
        100 /var/lib/dpkg/status
```
